version: "3.8"

services:
   newsapp:
     build:
       dockerfile: Dockerfile
       context: .
     restart: always
     ports:
        - "8010:8010"
     # Use a volume to mount the local environment file for environment variables.
     volumes:
        - "./.env:/app/.env"
